### ISSUE TITLE
Support for proxy configuration

### ISSUE THREAD

**Issue by techandsoftware** [kwoding/wiremock-rest-client#1]
We need to use a proxy in our corporate enviorment. Would it be possible to add an option to pass in a proxy, or maybe an agent, which is then passed onto node-fetch for requests?

There's an example here
https://github.com/bitinn/node-fetch/issues/79

**Comment by kwoding** [comment]
Yes, that is possible, will look into it. Is it ok to use an environment variable to set the proxy url?

**Comment by techandsoftware** [comment]
Yes that sounds good. Thanks for the quick response.

On 11 Dec 2019 20:46, Kwo Ding <notifications@github.com> wrote:

Yes, that is possible, will look into it. Is it ok to use an environment variable to set the proxy url?

**Comment by kwoding** [comment]
Released in version 1.2.0, check out the readme

**Comment by techandsoftware** [comment]
Brilliant 👍 thanks

On 12 Dec 2019 16:30, Kwo Ding <notifications@github.com> wrote:

Released in version 1.2.0, check out the readme
