### ISSUE TITLE
Use in browser

### ISSUE THREAD

**Issue by JoshKeegan** [kwoding/wiremock-rest-client#11]
Hi,
Is it possible to use this library on the client-side (in a web browser) rather than node?

I am trying to use it in Cypress tests which are executing in Chrome to test a Vue application with Server-Side rendering but I get the following error:
```
Error: Failed to execute 'fetch' on 'Window': Illegal invocation
```

Thanks!

**Comment by kwoding** [comment]
Thanks for adding this support, just released version 1.8.0
